FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim

WORKDIR /app

# Copy csproj and restore dependencies
COPY *.csproj ./
RUN dotnet restore ./dotnet-client.csproj

# Copy the rest of the code and build
COPY . ./
RUN dotnet build ./dotnet-client.csproj --configuration Release

ENTRYPOINT ["dotnet", "run", "--project", "./dotnet-client.csproj", "Producer"]